apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-demo-deployment
spec:
  selector:
    matchLabels:
      app: docker-k8s-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-k8s-demo
    spec:
      containers:
        - name: docker-k8s-demo
          image: bblaprib/nishitha143:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
